/* =====================================================================
   THE CONTENT-MODEL FOUNDATION  (Phase 2C-A)
   ---------------------------------------------------------------------
   Phase 2C-A added five optional fields to every page record -- type,
   publishedAt, excerpt, author, related -- and one top-level collection,
   `authors`. NOTHING READS ANY OF THEM YET. That is the whole claim of
   the phase, and a claim that something is inert is only worth making if
   it is measured, so this suite measures it.

   The strongest form of "inert" is not "no reader was added". It is: build
   the same brand twice, once from a record where these fields are absent
   and once where every one of them is filled in with a value a crawler
   would notice, and show that every generated byte is the same and that
   none of those values appears anywhere in the output. That is section 2,
   and it is the assertion the phase stands on.

   The rest establishes that the foundation is usable later without being
   usable now: the defaults are present and empty (so a reader can assume
   the key exists), a record written before the fields existed still
   resolves (so no row needs rewriting), and values written into them
   survive the read path intact (so the reader a later phase adds will
   find them).

   WHAT IS DELIBERATELY NOT ASSERTED. There is no assertion that a
   `taxonomy` key is absent. Categories and tags were deferred by the
   Phase 2C audit, and a test whose only purpose is to fail when a later
   phase adds a key is a test written to be deleted.
   ===================================================================== */
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const pbbake = require(path.join(ROOT, 'tools', 'lib', 'pbbake.js'));

let pass = 0, fail = 0; const fails = [];
const check = (n, c, e) => { c ? (pass++, console.log('  PASS  ' + n))
  : (fail++, fails.push(n), console.log('  FAIL  ' + n + (e !== undefined ? ' -> ' + JSON.stringify(e) : ''))); };

const tmpRoots = [];
function mktmp(tag) {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), 'cmodel-' + tag + '-'));
  tmpRoots.push(d); return d;
}
const rel = p => path.relative(ROOT, p).split(path.sep).join('/');
const sha = f => crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');

function walk(dir, base, out) {
  base = base || dir; out = out || [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : 1)) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, base, out);
    else out.push(path.relative(base, full).split(path.sep).join('/'));
  }
  return out;
}

function build(args) {
  try {
    const out = execFileSync(process.execPath,
      [path.join(ROOT, 'tools', 'build-site.js')].concat(args),
      { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    return { ok: true, out: out };
  } catch (e) { return { ok: false, out: (e.stdout || '') + (e.stderr || '') }; }
}

/* The five fields, named once. Every loop below reads this, so the suite
   cannot test four of them and quietly forget the fifth. */
const NEW_FIELDS = ['type', 'publishedAt', 'excerpt', 'author', 'related'];
const EMPTY = { type: '', publishedAt: '', excerpt: '', author: '', related: [] };

/* Values chosen so that if ANY of them reached the output, a grep would
   find it: each is a word that appears nowhere else in the repository. */
const FILLED = {
  type: 'zqguide',
  publishedAt: '2026-04-17',
  excerpt: 'ZQEXCERPTMARKER a summary that must not be rendered anywhere.',
  author: 'zqauthorid',
  related: ['about', 'contact']
};
const MARKERS = ['zqguide', '2026-04-17', 'ZQEXCERPTMARKER', 'zqauthorid'];

const WORK = mktmp('work');
const ROWS = path.join(WORK, 'rows'); fs.mkdirSync(ROWS, { recursive: true });

/* A CMS page record of the shape the admin's Create-a-page writes, minus
   the new fields. `extra` is how a test adds them -- or does not. */
function cmsPage(slug, extra) {
  return Object.assign({
    label: 'Model Probe', url: slug + '.html', slug: slug,
    title: 'Model Probe Page For The Content Model Foundation',
    metaDescription: 'A page used to prove that the Phase 2C-A content-model fields change nothing about what is published.',
    canonical: '', robots: { index: true, follow: true },
    heading: 'Model Probe', lead: 'A lead line.', body: '',
    og: { title: '', description: '', image: '' },
    twitter: { title: '', description: '', image: '' },
    breadcrumb: { label: 'Model Probe', show: true },
    schema: { webPage: true, breadcrumb: true, contactPage: false },
    inSitemap: true, status: 'published', updatedAt: '2026-09-28',
    builderMount: true,
    builder: { status: 'published', schemaVersion: 2, updatedAt: '2026-09-28',
      sections: [{ id: 's1', type: 'text', enabled: true,
        visibility: { desktop: true, tablet: true, mobile: true },
        style: {}, responsive: {},
        elements: [{ id: 'e1', type: 'heading',
          content: { text: 'A heading', level: 'h2' }, style: {}, responsive: {} }] }] }
  }, extra || {});
}

/* A whole record for a brand: its committed layer, plus the probe page.
   Built from the brand's own brand.js so the build is not refused for
   unpublishing what the committed layer publishes. */
function rowFor(brandId, file, pageExtra) {
  const base = JSON.parse(JSON.stringify(
    pbbake.brandRecord(fs.readFileSync(path.join(ROOT, 'brands', brandId, 'brand.js'), 'utf8'))));
  base.pages = base.pages || {};
  base.pages['model-probe'] = cmsPage('model-probe', pageExtra);
  const p = path.join(ROWS, file);
  fs.writeFileSync(p, JSON.stringify({ data: base, updated_at: '2026-09-28T21:00:00+00:00' }, null, 1));
  return p;
}

const CMS = pbbake.loadEngine(ROOT).CMS;
const DEFAULTS = JSON.parse(JSON.stringify(CMS.DEFAULTS));

/* ====================================================================
   1. THE DEFAULTS EXIST, AND ARE EMPTY
   ==================================================================== */
console.log('\n===== THE NEW DEFAULTS ARE PRESENT AND EMPTY =====');
{
  const slugs = Object.keys(DEFAULTS.pages);
  check('the shipped page set is still the same seven pages', slugs.length === 7, slugs);

  for (const f of NEW_FIELDS) {
    const missing = slugs.filter(s => !(f in DEFAULTS.pages[s]));
    check('every shipped page declares ' + f, missing.length === 0, missing);
  }
  for (const f of NEW_FIELDS) {
    const wrong = slugs.filter(s => JSON.stringify(DEFAULTS.pages[s][f]) !== JSON.stringify(EMPTY[f]));
    check('  and ships it empty (' + f + ' = ' + JSON.stringify(EMPTY[f]) + ')', wrong.length === 0,
      wrong.map(s => s + ' = ' + JSON.stringify(DEFAULTS.pages[s][f])));
  }
  check('related is an array, so the merge replaces it rather than blending two lists',
    slugs.every(s => Array.isArray(DEFAULTS.pages[s].related)));

  check('the authors collection exists', 'authors' in DEFAULTS);
  check('  and is an empty object, not an array',
    DEFAULTS.authors && typeof DEFAULTS.authors === 'object' &&
    !Array.isArray(DEFAULTS.authors) && Object.keys(DEFAULTS.authors).length === 0,
    DEFAULTS.authors);
  check('  and is NOT device-local, so it publishes with the rest of the record',
    CMS.localOnlyKeys().indexOf('authors') === -1, CMS.localOnlyKeys());

  /* The shared defaults must never carry content. An excerpt or an author
     name shipped here would appear on every brand at once. */
  const dirty = [];
  for (const s of slugs) for (const f of NEW_FIELDS) {
    const v = DEFAULTS.pages[s][f];
    if (Array.isArray(v) ? v.length : String(v) !== '') dirty.push(s + '.' + f);
  }
  check('no shipped page carries content in any new field', dirty.length === 0, dirty);
}

/* ====================================================================
   2. THE FIELDS CHANGE NOTHING THAT IS PUBLISHED
   --------------------------------------------------------------------
   Two builds of one brand: the probe page without the fields, and with
   every one of them filled in. Byte-for-byte the same, and no value
   anywhere in the output.
   ==================================================================== */
console.log('\n===== FILLING THE FIELDS IN CHANGES NO PUBLISHED BYTE =====');
{
  const without = rowFor('jsk-1.com', 'without.json', null);
  const withAll = rowFor('jsk-1.com', 'with.json', FILLED);
  const o1 = mktmp('without'), o2 = mktmp('with');
  const r1 = build(['jsk-1.com', '--row', rel(without), '--out', o1]);
  const r2 = build(['jsk-1.com', '--row', rel(withAll), '--out', o2]);
  check('the build succeeds with none of the new fields set', r1.ok, r1.out.slice(-400));
  check('the build succeeds with all of them set', r2.ok, r2.out.slice(-400));

  const d1 = path.join(o1, fs.readdirSync(o1)[0]);
  const d2 = path.join(o2, fs.readdirSync(o2)[0]);
  const f1 = walk(d1), f2 = walk(d2);
  check('both builds produce the same file set', JSON.stringify(f1) === JSON.stringify(f2),
    { onlyWithout: f1.filter(f => !f2.includes(f)), onlyWith: f2.filter(f => !f1.includes(f)) });

  const differing = f1.filter(f => f2.includes(f) && sha(path.join(d1, f)) !== sha(path.join(d2, f)));
  check('every generated file is byte-identical', differing.length === 0, differing);

  /* Said separately from the hash comparison: identical files could both
     contain a marker. These say the values are not published at all. */
  const hay = f2.filter(f => /\.(html|xml|txt|json)$/.test(f))
    .map(f => ({ f: f, s: fs.readFileSync(path.join(d2, f), 'utf8') }));
  for (const m of MARKERS) {
    check('no output file contains "' + m + '"',
      !hay.some(x => x.s.indexOf(m) > -1), hay.filter(x => x.s.indexOf(m) > -1).map(x => x.f));
  }
  check('the probe page was really generated (so the comparison means something)',
    f2.includes('model-probe.html'), f2.filter(f => /probe/.test(f)));
  check('  and is in the sitemap, as it was before',
    fs.readFileSync(path.join(d2, 'sitemap.xml'), 'utf8').includes('/model-probe.html'));
}

/* ====================================================================
   3. A RECORD WRITTEN BEFORE THE FIELDS EXISTED STILL RESOLVES
   ==================================================================== */
console.log('\n===== AN OLDER RECORD NEEDS NO REWRITING =====');
{
  /* The read path a build uses hands page records through whole. A page
     lacking the new fields must come back lacking them -- not defaulted,
     not dropped. */
  const old = { pages: { legacy: { url: 'legacy.html', slug: 'legacy', status: 'published' } } };
  const got = pbbake.pagesFromRecord(old);
  check('pagesFromRecord still returns a page that has none of the new fields',
    !!got.legacy && got.legacy.url === 'legacy.html', got);
  check('  and does not invent them', NEW_FIELDS.every(f => !(f in got.legacy)),
    NEW_FIELDS.filter(f => f in got.legacy));

  /* The merge chain is what supplies the defaults for the shipped pages,
     which is why no row has to be rewritten. */
  const stored = { pages: { about: { title: 'A stored title' } } };
  const merged = CMS.merge(DEFAULTS, stored);
  check('merging a stored record keeps what it says', merged.pages.about.title === 'A stored title');
  check('  and supplies every new field from the defaults',
    NEW_FIELDS.every(f => JSON.stringify(merged.pages.about[f]) === JSON.stringify(EMPTY[f])),
    NEW_FIELDS.map(f => f + '=' + JSON.stringify(merged.pages.about[f])));
  check('  and still supplies the authors collection', JSON.stringify(merged.authors) === '{}');

  /* A record that predates `authors` entirely. */
  const noAuthors = CMS.merge(DEFAULTS, { seo: { baseUrl: 'https://example.test' } });
  check('a record with no authors key reads as an empty collection',
    noAuthors.authors && Object.keys(noAuthors.authors).length === 0);
}

/* ====================================================================
   4. VALUES WRITTEN INTO THE FIELDS SURVIVE THE READ PATH
   --------------------------------------------------------------------
   So the reader a later phase adds will actually find them.
   ==================================================================== */
console.log('\n===== WHAT IS WRITTEN IS WHAT IS READ BACK =====');
{
  const rec = { pages: { g: Object.assign({ url: 'g.html', slug: 'g', status: 'published' }, FILLED) },
                authors: { zqauthorid: { name: 'A Name' } } };
  const got = pbbake.pagesFromRecord(rec);
  check('every new field survives pagesFromRecord unchanged',
    NEW_FIELDS.every(f => JSON.stringify(got.g[f]) === JSON.stringify(FILLED[f])),
    NEW_FIELDS.map(f => f + '=' + JSON.stringify(got.g[f])));

  /* The publish payload strips device-local keys only. A content
     collection must not be among them. */
  const local = CMS.localOnlyKeys();
  check('authors is not stripped from the publish payload', local.indexOf('authors') === -1, local);
  check('  and neither is pages, as before', local.indexOf('pages') === -1, local);

  /* Merging over a filled record must not blend the related list. */
  const blended = CMS.merge({ pages: { g: { related: ['x', 'y', 'z'] } } },
                            { pages: { g: { related: ['only'] } } });
  check('related replaces wholesale rather than merging two authors\' lists',
    JSON.stringify(blended.pages.g.related) === '["only"]', blended.pages.g.related);
}

/* ====================================================================
   5. NO READER LOOKS AT THEM YET
   --------------------------------------------------------------------
   The SEO computation is the one place a page record is turned into
   output. Asked for the same page twice, with and without the fields, it
   must answer identically.
   ==================================================================== */
console.log('\n===== THE SEO COMPUTATION IGNORES THEM =====');
{
  const src = {
    key: 'content-model-probe',
    brand: pbbake.brandRecord(fs.readFileSync(path.join(ROOT, 'brands', 'jsk-1.com', 'brand.js'), 'utf8')),
    row: null, baseUrl: 'https://example.test', noindex: false
  };
  const bare = cmsPage('model-probe', null);
  const full = cmsPage('model-probe', FILLED);
  /* seoEngine() merges `row` as a RECORD, not as the {data,updatedAt}
     wrapper a Supabase read returns -- tools/lib/sitekit.js unwraps it
     before tools/lib/brandkit.js builds this object. Passing the wrapper
     here resolves no page and every comparison below would then pass on
     two nulls, so the resolution is asserted before anything is compared. */
  let seq = 0;
  const tagsFor = page => pbbake.seoTags(ROOT,
    Object.assign({}, src, { key: src.key + ':' + (seq++),
      row: { pages: { 'model-probe': page },
             seo: { baseUrl: 'https://example.test', siteName: 'Example' } } }),
    'model-probe', { breadcrumbNav: true });
  const a = tagsFor(bare), b = tagsFor(full);
  check('the engine resolved the page and computed a title', !!a && !!a.title, a && a.title);
  check('  and a canonical, a description and a WebPage block',
    !!a && !!(a.links && a.links[0] && a.links[0].href) &&
    a.metas.some(m => m.name === 'description' && m.content) &&
    !!(a.jsonLd && a.jsonLd.ldPage && a.jsonLd.ldPage['@type']),
    a && { canonical: a.links && a.links[0], ld: a.jsonLd && a.jsonLd.ldPage });
  check('title, metas, canonical and JSON-LD are identical with the fields filled in',
    !!a && !!b && JSON.stringify(a) === JSON.stringify(b),
    { without: JSON.stringify(a).slice(0, 300), with: JSON.stringify(b).slice(0, 300) });
  check('  and no marker reached any computed value',
    !!b && MARKERS.every(m => JSON.stringify(b).indexOf(m) === -1),
    b && MARKERS.filter(m => JSON.stringify(b).indexOf(m) > -1));
}

/* ====================================================================
   6. WHITE LABEL: THREE BRANDS, NO CROSSING
   ==================================================================== */
console.log('\n===== THE FIELDS ARE PER-BRAND LIKE EVERY OTHER CONTENT KEY =====');
{
  /* JSK1 carries the filled fields; Playzone9 carries none. Neither
     build may show any sign of the other. */
  const aRow = rowFor('jsk-1.com', 'wl-a.json', FILLED);
  const bRow = rowFor('playzone9.app', 'wl-b.json', null);
  const oa = mktmp('wl-a'), ob = mktmp('wl-b');
  const ra = build(['jsk-1.com', '--row', rel(aRow), '--out', oa]);
  const rb = build(['playzone9.app', '--row', rel(bRow), '--out', ob]);
  check('brand A builds with the fields filled in', ra.ok, ra.out.slice(-400));
  check('brand B builds with none of them', rb.ok, rb.out.slice(-400));

  const db = path.join(ob, fs.readdirSync(ob)[0]);
  const bText = walk(db).filter(f => /\.(html|xml|txt)$/.test(f))
    .map(f => fs.readFileSync(path.join(db, f), 'utf8')).join('\n');
  for (const m of MARKERS) {
    check('brand B\'s output carries no trace of brand A\'s "' + m + '"', bText.indexOf(m) === -1);
  }

  /* Brand B's own output must also be unchanged by the fields existing at
     all, which is the same byte comparison as section 2 on a second brand. */
  const bRow2 = rowFor('playzone9.app', 'wl-b2.json', FILLED);
  const ob2 = mktmp('wl-b2');
  const rb2 = build(['playzone9.app', '--row', rel(bRow2), '--out', ob2]);
  const db2 = path.join(ob2, fs.readdirSync(ob2)[0]);
  check('brand B builds with them too', rb2.ok, rb2.out.slice(-400));
  const bDiff = walk(db).filter(f => sha(path.join(db, f)) !== sha(path.join(db2, f)));
  check('  and its output is byte-identical either way', bDiff.length === 0, bDiff);

  /* A third brand that is only a directory, to show this is a property of
     the record rather than of the two brands in this repository. */
  const synth = path.join(__dirname, 'fixtures', 'brands');
  if (fs.existsSync(synth)) {
    const root = mktmp('third');
    const brandsDir = path.join(root, 'brands');
    fs.cpSync(synth, brandsDir, { recursive: true });
    const id = fs.readdirSync(brandsDir, { withFileTypes: true })
      .filter(e => e.isDirectory()).map(e => e.name).sort()[0];
    const seo = JSON.parse(fs.readFileSync(path.join(ROOT, 'tools', 'seo-config.json'), 'utf8'));
    seo.seo = seo.seo || {};
    seo.seo.baseUrl = 'https://' + id;
    fs.writeFileSync(path.join(brandsDir, id, 'seo-config.json'), JSON.stringify(seo, null, 2) + '\n');

    const base = JSON.parse(JSON.stringify(
      pbbake.brandRecord(fs.readFileSync(path.join(brandsDir, id, 'brand.js'), 'utf8'))));
    base.pages = base.pages || {};
    base.pages['model-probe'] = cmsPage('model-probe', FILLED);
    base.authors = { zqauthorid: { name: 'A Name' } };
    const row3 = path.join(ROWS, 'wl-c.json');
    fs.writeFileSync(row3, JSON.stringify({ data: base, updated_at: '2026-09-28T21:00:00+00:00' }, null, 1));
    const oc = mktmp('wl-c');
    const rc = build([id, '--brands', rel(brandsDir), '--row', rel(row3), '--out', oc]);
    check('a third brand builds with the new fields and an authors collection', rc.ok, rc.out.slice(-500));
    const dc = path.join(oc, fs.readdirSync(oc)[0]);
    const cText = walk(dc).filter(f => /\.(html|xml|txt)$/.test(f))
      .map(f => fs.readFileSync(path.join(dc, f), 'utf8')).join('\n');
    for (const m of MARKERS) {
      check('  and publishes no trace of "' + m + '" either', cText.indexOf(m) === -1);
    }
    check('  while still generating its page on its own domain',
      cText.indexOf('https://' + id + '/model-probe.html') > -1);
  }
}

for (const d of tmpRoots) { try { fs.rmSync(d, { recursive: true, force: true }); } catch (e) {} }

console.log(`\n==== ${pass} passed, ${fail} failed ====`);
if (fails.length) console.log('FAILED:', fails.join(' | '));
process.exit(fail ? 1 : 0);
